spring.application.name=vehicle-registry

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/easyfind_vehicles
spring.datasource.username=postgres
spring.datasource.password=1234
